# Simple workflow for deploying static content to GitHub Pages
name: Run tests

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Run build on latest ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 21
        cache: 'npm'
    # Install dependencies using clean install to avoid package lock updates
    - name: Install dependencies
      run: npm ci
    # Run the tests
    - name: Build
      run: npm test
